services:
  - type: web
    name: alex-messenger-server
    env: python
    plan: free # important for free tier
    buildCommand: "./.render-build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT 'pc_app.server:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9 # Match your local Python version
      - key: DATABASE_URL
        fromDatabase:
          name: alex-messenger-db
          property: connectionString

databases:
  - name: alex-messenger-db
    plan: free # important for free tier
    databaseName: alex_messenger
    user: alex_messenger_user
